/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Type.h
 * Generated on: Mon Apr 22 23:49:45 EET
 ********************************************************************/

#ifndef RTE_TYPE_H
#define RTE_TYPE_H


#include "Rte.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/**************************** datatypes ******************************/

typedef unsigned char uint8;


/********************* mode declaration groups ***********************/


/********************** per instance memories ************************/


/******************* implicit buffer declaration *********************/

typedef struct {
	uint8 value;
} Rte_DE_uint8;


/******************** component data structures **********************/

/*********************************************************************
 * component data structure for SWC: DoorSensorAbstractionSWC 
 *********************************************************************/
typedef struct Rte_CDS_DoorSensorAbstractionSWC
{
	/* Data Handles section*/
	Rte_DE_uint8 *ReadDoorSensor_Pport_SR_DoorState_DoorState;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_DoorSensorAbstractionSWC;

/*********************************************************************
 * component data structure for SWC: DoorLockAlgoSW 
 *********************************************************************/
typedef struct Rte_CDS_DoorLockAlgoSW
{
	/* Data Handles section*/
	Rte_DE_uint8 *DoorLockAlgo_Rport_SR_DoorState_DoorState;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_DoorLockAlgoSW;


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_TYPE_H */
