/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstractionSWC_.c
 * Generated on: Mon Apr 22 23:49:45 EET
 ********************************************************************/

#include "string.h"
#include "Rte_DoorSensorAbstractionSWC.h"


extern Rte_DE_uint8 ReadDoorSensor_Pport_SR_DoorState_DoorState;


const Rte_CDS_DoorSensorAbstractionSWC Rte_Instance_DoorSensorAbstractionSWC = {
&ReadDoorSensor_Pport_SR_DoorState_DoorState
};

const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC = &Rte_Instance_DoorSensorAbstractionSWC;




void Rte_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_Pport_SR_DoorState_DoorState (uint8 DoorState)
{
	(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_Pport_SR_DoorState_DoorState->value = DoorState;
}
uint8* Rte_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_Pport_SR_DoorState_DoorState(void)
{
	return &(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_Pport_SR_DoorState_DoorState->value;
}
