/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorLockAlgoSW.h
 * Generated on: Mon Apr 22 23:49:45 EET
 ********************************************************************/

#ifndef RTE_DOORLOCKALGOSW_H
#define RTE_DOORLOCKALGOSW_H

#include "Rte_DoorLockAlgoSW_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_DoorLockAlgoSW * const Rte_Inst_DoorLockAlgoSW;

/************************ application errors *************************/

#define RTE_E_IF_CS_LedSwitch_E_Not_Ok ((Std_ReturnType)1)
#define RTE_E_IF_CS_LedSwitch_E_Ok ((Std_ReturnType)0)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		Rport_SR_DoorState
 * Interface:	IF_SR_DoorState
 * DataElement:	DoorState
 * Runnable:	DoorLockAlgo
 *****************************************************/
extern uint8 Rte_IRead_DoorLockAlgoSW_DoorLockAlgo_Rport_SR_DoorState_DoorState (void);
#ifndef IN_RTE_C
#define Rte_IRead_DoorLockAlgo_Rport_SR_DoorState_DoorState() \
	Rte_IRead_DoorLockAlgoSW_DoorLockAlgo_Rport_SR_DoorState_DoorState()
#endif

/*****************************************************
 * Port: 		Rport_CS_LedSwitch
 * Interface:	IF_CS_LedSwitch
 * Operation:	LED_Switch
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_DoorLockAlgoSW_Rport_CS_LedSwitch_LED_Switch (uint8 LED_State);
#ifndef IN_RTE_C
#define Rte_Call_Rport_CS_LedSwitch_LED_Switch(LED_State) \
	Rte_Call_DoorLockAlgoSW_Rport_CS_LedSwitch_LED_Switch(LED_State)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	DoorLockAlgo
 * Period:		0.012
 *****************************************************/
extern void DoorLockAlgo_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_DoorLockAlgoSW_Rport_CS_LedSwitch_LED_Switch)(uint8 LED_State);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORLOCKALGOSW_H */
