/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstractionSWC.h
 * Generated on: Mon Apr 22 23:49:45 EET
 ********************************************************************/

#ifndef RTE_DOORSENSORABSTRACTIONSWC_H
#define RTE_DOORSENSORABSTRACTIONSWC_H

#include "Rte_DoorSensorAbstractionSWC_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/


/************************* instance handle ***************************/

extern const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC;

/************************ application errors *************************/

#define RTE_E_IF_CS_LedSwitch_E_Not_Ok ((Std_ReturnType)1)
#define RTE_E_IF_CS_LedSwitch_E_Ok ((Std_ReturnType)0)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		Pport_SR_DoorState
 * Interface:	IF_SR_DoorState
 * DataElement:	DoorState
 * Runnable:	ReadDoorSensor
 *****************************************************/
extern void Rte_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_Pport_SR_DoorState_DoorState (uint8 DoorState);
#ifndef IN_RTE_C
#define Rte_IWrite_ReadDoorSensor_Pport_SR_DoorState_DoorState(RTEData) \
	Rte_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_Pport_SR_DoorState_DoorState(RTEData)
#endif
extern uint8* Rte_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_Pport_SR_DoorState_DoorState(void);
#ifndef IN_RTE_C
#define Rte_IWriteRef_ReadDoorSensor_Pport_SR_DoorState_DoorState() \
	Rte_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_Pport_SR_DoorState_DoorState()
#endif

/*****************************************************
 * Port: 		Pport_CS_LedSwitch
 * Interface:	IF_CS_LedSwitch
 * Operation:	LED_Switch
 *****************************************************/
extern Std_ReturnType LedSwitch_Runnable(uint8 LED_State) ;


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	ReadDoorSensor
 * Period:		0.01
 *****************************************************/
extern void ReadDoorSensor_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_DOORSENSORABSTRACTIONSWC_H */
